### ISSUE TITLE
train error:ValueError: invalid literal for int() with base 10:

### ISSUE THREAD

**Issue by HBing110** [hcw-00/PatchCore_anomaly_detection#50]
Epoch 0: 100%|█████████████████████████████████████████████████████Epoch 0: 100%|████████████████████████████████████████████████████████████████| 62/62 [00:20<00:00,  2.98it/s, v_num=6]Traceback (most recent call last):
  File "train.py", line 440, in <module>
    trainer.fit(model)
  File "F:\ProgramData\Anaconda3\envs\patchcore\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "F:\ProgramData\Anaconda3\envs\patchcore\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "F:\ProgramData\Anaconda3\envs\patchcore\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 737, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "F:\ProgramData\Anaconda3\envs\patchcore\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1168, in _run
    results = self._run_stage()
  File "F:\ProgramData\Anaconda3\envs\patchcore\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1254, in _run_stage
    return self._run_train()
  File "F:\ProgramData\Anaconda3\envs\patchcore\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1285, in _run_train
    self.fit_loop.run()
  File "F:\ProgramData\Anaconda3\envs\patchcore\lib\site-packages\pytorch_lightning\loops\loop.py", line 201, in run
    self.on_advance_end()
  File "F:\ProgramData\Anaconda3\envs\patchcore\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 286, in on_advance_end
    epoch_end_outputs = self.trainer._call_lightning_module_hook("training_epoch_end", epoch_end_outputs)
  File "F:\ProgramData\Anaconda3\envs\patchcore\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1552, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "train.py", line 354, in training_epoch_end
    selected_idx = selector.select_batch(model=self.randomprojector, already_selected=[], N=int(total_embeddings.shape[0]*args.coreset_sampling_ratio))
ValueError: invalid literal for int() with base 10: '0.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.010.0

**Comment by edwardcho** [comment]
Hello Sir,

I also met same error......

**Comment by edwardcho** [comment]
Hello Sir,

I found similar articles about this error.
[link](https://github.com/hcw-00/PatchCore_anomaly_detection/issues/20)

Thanks,
Edward Cho.
